### ISSUE TITLE
Missing py.typed file in package

### ISSUE THREAD

**Issue by johanvergeer** [godatadriven/pydantic-avro#108]
Hi,

I've encountered an issue with the pydantic-avro package when using mypy for static type checking. The package is missing a py.typed file, which causes mypy to raise the following error:

```shell
error: Skipping analyzing "pydantic_avro.base": module is installed, but missing library stubs or py.typed marker  [import-untyped]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

To reproduce:

1. Install the pydantic-avro package.
2. Run mypy on a file that imports pydantic_avro.base.

Suggested solution:
Please include a `py.typed` file in the package to indicate that it supports type checking.

Reference:
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

Thank you!

**Comment by dan1elt0m** [comment]
Added in 0.7.1. Thanks for raising the issue!
