### ISSUE TITLE
Unknown type found: 'object'

### ISSUE THREAD

**Issue by danhje** [godatadriven/pydantic-avro#7]
First of all, let me thank you for making this package open source. I've been looking for this for a while. 

Ok, here's the issue:
```python
class Demo(AvroBase):
    attr: Dict[str, str]

Demo.avro_schema()
# RuntimeError: Unknown type found: 'object'
```

I think a correct avro schema would look something like this:
```json
{
  "name": "Demo",
  "type": "record",
  "fields": [
    {
      "name": "attr",
      "type": {
        "type": "map",
        "values": "string"
      },
      "additionalProperties": {
        "type": "string"
      }
    }
  ],
  "namespace": "Demo"
}
```

**Comment by danhje** [comment]
The code below, inserted [here](https://github.com/godatadriven/pydantic-avro/blob/main/src/pydantic_avro/base.py#L65), seems to do the trick. I might submit a PR later, if I have time.

```python
        elif t == "object" and value.get("additionalProperties") is not None:
            items = value.get("additionalProperties")
            tn = get_type(key, items, prefix)
            # If items in array are object:
            if "$ref" in items:
                tn = tn["type"]
            # If items in array are a logicalType
            if (
                isinstance(tn, dict)
                and isinstance(tn.get("type", {}), dict)
                and tn.get("type", {}).get("logicalType") is not None
            ):
                tn = tn["type"]
            avro_type_dict["type"] = {"type": "map", "values": tn}

```

**Comment by ffinfo** [comment]
Thank you for this feedback, will add this. If any other types are still missing please report them I will build them in or do a PR yourself.

The is instance will not work because it's not yet an instance. Still there is an other way of doing this. Will make a PR for this

**Comment by ffinfo** [comment]
See PR above for the fix.
Version 0.2.0 now has Avro map support.
https://pypi.org/project/pydantic-avro/0.2.0/

Thanks again for the feedback.

**Comment by ffinfo** [comment]
Version 0.2.1 now also with complex value types in a map. So this should now also work:
```python
class Nested(AvroBase):
    c1: str

class Test(AvroBase):
    c1: Dict[str, Nested]
```

**Comment by danhje** [comment]
Thanks for adding map support so quickly.
